# Generated by Django 5.1.4 on 2024-12-31 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rest_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='餐厅ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='餐厅名称')),
                ('dianping_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='大众点评ID')),
                ('avg_rating', models.FloatField(db_index=True, default=0, verbose_name='平均总评分')),
                ('avg_flavor_rating', models.FloatField(default=0, verbose_name='平均口味评分')),
                ('avg_env_rating', models.FloatField(default=0, verbose_name='平均环境评分')),
                ('avg_service_rating', models.FloatField(default=0, verbose_name='平均服务评分')),
                ('review_count', models.IntegerField(db_index=True, default=0, verbose_name='评论数量')),
            ],
            options={
                'verbose_name': '餐厅',
                'verbose_name_plural': '餐厅',
                'indexes': [models.Index(fields=['avg_rating', 'review_count'], name='recommender_avg_rat_4a81f1_idx'), models.Index(fields=['avg_flavor_rating'], name='recommender_avg_fla_001f68_idx'), models.Index(fields=['avg_env_rating'], name='recommender_avg_env_68bee5_idx'), models.Index(fields=['avg_service_rating'], name='recommender_avg_ser_3ec278_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='总体评分')),
                ('rating_env', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='环境评分')),
                ('rating_flavor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='口味评分')),
                ('rating_service', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='服务评分')),
                ('timestamp', models.DateTimeField(verbose_name='评分时间')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recommender.restaurant', verbose_name='餐厅')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
                'indexes': [models.Index(fields=['user_id', 'restaurant'], name='recommender_user_id_96c5e4_idx'), models.Index(fields=['timestamp'], name='recommender_timesta_a40159_idx')],
                'unique_together': {('user_id', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='关联权重')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='recommender.restaurant', verbose_name='源餐厅')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='recommender.restaurant', verbose_name='目标餐厅')),
            ],
            options={
                'verbose_name': '餐厅关联',
                'verbose_name_plural': '餐厅关联',
                'unique_together': {('source', 'target')},
            },
        ),
    ]
